-- Reset overpricing artifacts so the new agent-driven pipeline can reprocess from scratch.
--
-- Context: the OVERPRICING analysis was rewritten into a 2-pass pipeline where
-- statistical strategies populate PriceAnalysis (Pass 1) and a Claude-based
-- evaluator decides whether to create an alert (Pass 2). The old pipeline
-- created alerts directly from statistics and produced known false positives
-- (e.g. "PRESTAÇÃO DE SERVIÇO" flagged CRITICAL without context).
--
-- This migration:
--   1. Deletes all OVERPRICING alerts (old format — to be regenerated by the
--      new evaluator with proper context, paramsByLocale and derived estimates).
--   2. Deletes AiAnalysis rows from the interim/old overpricing screening so
--      Pass 2 re-evaluates every flagged item against the new logic.
--
-- PriceAnalysis rows are PRESERVED. Pass 1 strategies use `priceAnalyses: { none: ... }`
-- to avoid reprocessing — keeping them is cheaper and the data is still valid.
--
-- Idempotent: re-running is a no-op (DELETE on empty set).

BEGIN;

-- 1. Drop all OVERPRICING alerts produced by the previous (statistics-driven) pipeline.
DELETE FROM alerts
WHERE type = 'OVERPRICING';

-- 2. Drop any AiAnalysis records produced by the interim screening or by the new
--    evaluator so it re-runs against every still-flagged PriceAnalysis. The
--    `analysisType` values come from screen-overpricing-alert.ts (removed) and
--    the new evaluate-overpricing.ts.
DELETE FROM ai_analyses
WHERE "analysisType" IN ('overpricing_screening', 'overpricing_evaluation');

COMMIT;
