-- Reset AI_FLAG alerts so the analyzeAi pipeline regenerates them with neutralized wording.
--
-- Context: PR #5 neutralized the analyze-ai prompt (no "fraude", "corrupção",
-- "suspeito", etc.) but only included a backfill that updates the AI_FLAG
-- title. The description is copied from data.findings.summary verbatim — and
-- summaries produced by the OLD prompt still carry accusatory language
-- ("indícios graves de irregularidade", "altíssimo risco de fraude", etc.).
--
-- This migration:
--   1. Deletes all AI_FLAG alerts so they are regenerated by the new prompt.
--   2. Deletes ai_analyses rows of type 'risk_assessment' — required because
--      analyzeAi() filters procurements with `analyses: { none: {} }`, so the
--      cron would otherwise skip every procurement that already had an AI run.
--
-- The analyzeAi cron will repopulate both tables on the next run (only for
-- procurements that still have any alerts, per the same filter at line 27 of
-- analyze-ai.ts). Cost note: ~241 AI calls will re-run on the next analyze
-- cron (Sonnet 4, ~2k output tokens each).
--
-- Idempotent: re-running is a no-op (DELETE on empty set).

BEGIN;

-- 1. Drop all AI_FLAG alerts (old wording — to be regenerated by the new prompt).
DELETE FROM alerts
WHERE type = 'AI_FLAG';

-- 2. Drop the risk_assessment analyses so analyzeAi reprocesses each procurement.
--    'risk_assessment' is the only analysisType produced by analyze-ai.ts (line 85).
DELETE FROM ai_analyses
WHERE "analysisType" = 'risk_assessment';

COMMIT;
