-- CreateEnum
CREATE TYPE "TransactionCategory" AS ENUM ('CREDIT_CARD', 'FOOD', 'HOUSING', 'TRANSPORTATION', 'HEALTH', 'EDUCATION', 'LEISURE_ENTERTAINMENT', 'CLOTHING_ACCESSORIES', 'PERSONAL_EXPENSES', 'INSURANCE_PENSIONS', 'INVESTMENTS', 'DEBTS_LOANS');

-- AlterTable
ALTER TABLE "Transaction" ADD COLUMN     "category" "TransactionCategory" NOT NULL DEFAULT 'CREDIT_CARD';
