export enum ExpenseCategory {
  CREDIT_CARD = 'CREDIT_CARD',
  FOOD = 'FOOD',
  HOUSING = 'HOUSING',
  TRANSPORTATION = 'TRANSPORTATION',
  HEALTH = 'HEALTH',
  EDUCATION = 'EDUCATION',
  LEISURE_ENTERTAINMENT = 'LEISURE_ENTERTAINMENT',
  CLOTHING_ACCESSORIES = 'CLOTHING_ACCESSORIES',
  PERSONAL_EXPENSES = 'PERSONAL_EXPENSES',
  INSURANCE_PENSIONS = 'INSURANCE_PENSIONS',
  INVESTMENTS = 'INVESTMENTS',
  DEBTS_LOANS = 'DEBTS_LOANS',
  TAXES = 'TAXES',
}

export enum IncomeCategory {
  SALARY = 'SALARY',
  BUSINESS = 'BUSINESS',
  DIVIDENDS = 'DIVIDENDS',
  INTEREST = 'INTEREST',
  RENTAL = 'RENTAL',
  PENSION = 'PENSION',
  GIFTS = 'GIFTS',
  OTHER = 'OTHER',
}
